module.exports = (bot, message, args, Discord) => {
    var orhanassadov = [
        "hahahhahah wie crazy hahah",
        "ich würde feuste. ferteilen",
        "pummpen mit brudi",
        "hahahah hette es das ma früher ihn tv gegeben dan were ich vol der ferbrecher hahah",
        "crazy grad is ein bommber flugzeug über meiner wonung vorbei geflogen vol panik dachte jetzt gehts los crank",
        "Ich und er gönn und richtig chicken winghs hänchen schenkel kroketen fur mehr masse yeeeaaa",
        "Bssssss ich bin eine bine bssssssssssssssssssssy - Ich besteube dich. Bssss. Bssssssss",
        "Nach training erst ma ihns ghetto hahahah killa style",
        "Die brrass tragen. Hemmt und lackschuu",
        "Ich und mein bruder. Aggresiv und besoffen kommt uns schief k.o vor allem schlampen die denken die können mein bruder reinlegen bro.s bevor hou.s r live ihr bitches",
        "ich danke alle die mir gratulirt haben zum b day hab ihn im knast gefeiert tod aber ich gebe nich auf fortsezung folgt 23 jahre ald geworden 23 stunden zelle gekrigt hahaha pasirt nur mir",
        "Entlich 4 wochen jva münster jetz drausen freeeeee an mein b day krank 23 jahre ald geworden und vom stard 23 stunden zele gekrigt passiert nur mir fick den richter nur gott kann mich richten",
        "hahahah beste Mama die es je auf der weld gibt is genau so cool wie ein Kollege eben meine Mama liebe dich Mama peace leute",
        "hahah wat ein kleiner kakvogel direkt baba scheele bei so einer Missgeburt hahah",
        "Fick you",
        "Krank aber troztem am traniren gib ihn",
        "Mir ghetz wider besser aber dise Kak antibiotika kan nich trinken alleine zuhause",
        "Ey is das Kake singel zu sein misse",
        "Brudi am fly hafen gleich gehtz los ay geht hayyyy and the flayy",
        "Fuck of nimanden kan man vertauen wie 2pac es sagt 50 niggas mit ak47 ficken alle und ich gebe ihn recht weil alle gefickt sind ihr vozzen",
        "Entlich is. Es da felt der film dsn hab ich alles gib ihn zokken",
        "Gib ihn burger mit schampinion bacon zwibel gurke bulete wurst kase beste nen ich schwabel burger",
        "Fakker abend mit mein houmy bro",
        "perfekte breune hamma selbstverlibt",
        "fals es keiner weis das zelt nich der schwarze is der neue der 2014 raus kommt",
        "Boa was krass man gta hat sich selbst übertrofen alter torados gibs da auch schon wie fätt",
        "Schiesse us das klar da hat man kein bock mehr scheiss Laune",
        "Man kent freunde aber man merkt ers später was das für linke vozen sind ich bleib bei mein brüder den die haben respekt zu mir und ich zu ihnen fuck of the rest bitches",
        "Bus fahrkate is weg SCHEISSE",
        "korekt heute zihe ich ihn meine neuen Wohnung ein und es wird auf den Balkon geraucht",
        "erlich best tag mit wowa und toby senden Freibad halen bad oder was das is widerholen wir jungs",
        "boa wen das mein Hund were ich würde da ein masserka machen und die scheiss bullen alle umbringen der arme Hund sowas könn nur bullen machen weil sie alle hurensöner sind ihn jeden land",
        "baaa wie krass is das den ers vol das sommer filing und hjetz wider typisch Deutschland gewiter alter",
        "krass mit kalep Roman und cara und marivn delkus gepint und freitag geht ab haffen fest wer mit will schrieb komi und schreibt ich komm mit treffen ander grossen Uhr ich poste wan",
        "volll mattzo ey haha",
        "doch keine bommbe wonung bei cheas hat gebratnt gassflaschen drine jeder 300 meter abstand das geilste ein opa is durch die absperung gelaufen dan meine der bulle jaja durch die absperung mogeln das geht ja nich noch einma dan nem ich sie mit und der opa ja leck mich doch am arsch hahahahahah zu geil",
        "bin en leuten wen was is schreibt einfach aber wundert euch nich das nich nich back schreibe",
        "Wegen sowas wie dich mach ich mich nich mer vertig und kämpfen ers recht nich mehr",
        "Booooom die bommbe is geplazt ich hab mein haupt gib ihn geschaft",
        "Geil grad von ein kak audi tt überfaren wurden linkes ohr taub weil ich auf die kak haube geknald bin wegen scheiss frau am steuer dan sickt die voze mich an warum ich über zebraschreifen gelaufen bin geil kaputess ohr und die hure kan ohne nix weiter aber gut dafür das ich ihr ne flasche wodka auf die haube geknald hab scheiss nutte",
        "Scheisse einma den fussgeprelt anstad zum sport kan ich hir weiter arbeiten und abgammeln wtf",
    ];
    message.channel.send(orhanassadov[Math.floor(Math.random() * orhanassadov.length)]);
    message.delete();
};